### ISSUE TITLE
Usage in browser

### ISSUE THREAD

**Issue by olemp** [SharePoint/pnp-js-provisioning#1]
@patrick-rodgers  You say in the Community Call meeting from December 16 (https://www.youtube.com/watch?v=SGJXq1nuMoU) that usage of the JS provisioning in the browser is not recommended, but do we still want to support it? I would love it if we could. 

The initial commit of the provisioning part was from https://github.com/Puzzlepart/js-sites-core which was built for a specific customer case which didn't allow us to use any automatic provisioning. With WSPs being a thing from the past, client side provisioning was the only way to go. PnP-Provisioning, but in the browser, using the same schema format.

For simple subsite provisioning on-the-fly https://github.com/Puzzlepart/js-sites-core has worked very well for us, and we would love to be able to contribute to a common JS provisioning library which can be used both in Node and Browser.

**Comment by olemp** [comment]
For browser usage Schema should support .JSON files residing in a SharePoint library.

**Comment by patrick-rodgers** [comment]
Hi @olemp,

We are not doing anything to _block_ usage of the library in the browser and the package .js files should work there, however it isn't something I feel we should encourage. If folks have that need they can, but issue which are submitted along the lines of "my client closed the browser window and provisioning failed..." wouldn't really be supportable - do you agree?

There  were several issues with the provisioning code as it sat but effectively they can be reduced to two:

1. The code did not work in nodejs.
2. The code was submitted, merged, and then abandoned.

1 - is the reason I refactored what was there to provide very basic support for provisioning in nodejs, create a project directory with updated gulp functionality, and simplify the code. I consider this just a starting point, see point #2.

2 - It was awesome of you to submit the code to the library back at the beginning, in fact I believe it was one of the first large contributions. But then it wasn't upgraded, maintained, or documented. It also did not work in nodejs. The pnp core team has committed significant work to a provisioning engine using CSOM (and also callable from PowerShell) so it didn't make sense for us to also commit (we simply don't have folks to do it) to maintaining a second library. However we recognize that there may exist a desire for a JavaScript based provisioning library so we felt the best path was to break out the code and give it its own home.

I took the step of updating the project to use nodejs, updated gulp commands, and generally match the sp-pnp-js stuff to provide a similar development experience. Will talk about it some on this week's call - but now it is up to the community what becomes of this library. What I have added here is in no way finished/perfect/done and should evolve inline with what folks want to contribute. I 100% agree the schemas should match between the two engines as much as possible, something I didn't do as I ported over the code. I just wanted to get  starting point in place for the community.

To your second point, sure it should support whatever the community wants to contribute. But one thing to think about is reusing existing functionality such as the readJSON capability from the sp-pnp-js library to get the template, and then pass that to the provisioning - not necessarily duplicate the file read behavior.

**Comment by olemp** [comment]
Great stuff @patrick-rodgers!

It wasn't meant as criticism in any way. 

I agree with everything above, and we can't support issues like _"my client closed the browser window and provisioning failed..."_, but that's the usecase I have. We want to use this library as a WSP web template + client side setup replacement for customers who don't have the budgets for remote provisioning using e.g. PnP Sites Core.

Would love to contribute!

**Comment by patrick-rodgers** [comment]
Awesome! Look forward to growing this library and am excited to see your contributions. This would also be a great opportunity for anyone looking to take a larger role in the PnP community and really drive JS provisioning.

And don't worry - didn't take anything you said badly, all good :)

**Comment by VesaJuvonen** [comment]
Closing this issue, since it's not really a issue. I think the discussion is already ended. Thx for your input.
