### ISSUE TITLE
Update package.json refs to latest

### ISSUE THREAD

**Issue by patrick-rodgers** [SharePoint/pnp-js-provisioning#15]
It would be a good idea to update the package.json refs to latest and updated any associated tasks or code based on those changes. The dependencies are fairly outdated at this point from when I made the copy.

**Comment by olemp** [comment]
Updated sp-pnp-js to `^2.0.5` which is most important update. Not sure if updating all deps to latest is a good idea. What do you think @patrick-rodgers?

**Comment by patrick-rodgers** [comment]
I try and update the dependencies when I do a release for the core library. Sometimes that is just updating the number to get the latest - but other times I have to rewrite/rework things, especially in the gulp tasks when something changes there. Up to you how you want to manage it - but I do try and keep things up to date (mostly).
