### ISSUE TITLE
Merge master and publish 0.8.0 to master

### ISSUE THREAD

**Issue by olemp** [SharePoint/pnp-js-provisioning#26]
Could master be merged with dev and the package published to npm?

**Comment by patrick-rodgers** [comment]
So yes, we could do that. OR we were just discussing in the core team that it is likely appropriate if folks want to commit to maintain this that we move it to the new org and publish from there (not technically necessary, but I think it helps). I haven't really been following the state of this project as it seemed dormant the last few times I checked. And it is easy to move as we have no current releases.

Would love to see it updated to use the new pnp scoped libraries as well.

**Comment by olemp** [comment]
I could add it to https://github.com/pnp/pnp if you'd like, and we can discontinue this.

At least me and my team are planning on doing more work on this. We would e.g. like to use it with the modern experience to support user extensions that are applied client side.

**Comment by patrick-rodgers** [comment]
Let me then create a repo for you to put it in and you can create a PR there. Will update this shortly.

**Comment by patrick-rodgers** [comment]
https://github.com/pnp/sp-js-provisioning there you go :)

**Comment by patrick-rodgers** [comment]
@olemp - when you're ready if you want to grab everything and create a new PR to that repo I linked above we can get it merged and get a release out. Thanks!

**Comment by olemp** [comment]
Sorry, bit slow here. Working on doing it asap 🔨

**Comment by olemp** [comment]
https://github.com/pnp/sp-js-provisioning/pull/2
